global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'policy-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['policy-service:8081']

  - job_name: 'quote-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['quote-service:8082']

  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:8083']

  - job_name: 'document-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['document-service:8084']

  - job_name: 'search-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['search-service:8085']
